# -*- coding: utf-8 -*-
"""課題３.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EvEVR3tq9dss6a_9BowCCzMzOoJP1qLM
"""

#おまじない
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

A=tf.constant(3) #３が入っているノードを作成
B=tf.placeholder(tf.int32) #整数型のプレースホルダph1を作成
hiku=B-A #ノードAからノードBを引くノードを作成

#実行
sess=tf.Session()
print(sess.run(hiku,feed_dict={B:5})) #プレースホルダであるBに値５を渡してノードhikuを実行
sess.close() #ノードの実行終了

#おまじない
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

#それぞれのプレースホルダを作成　まだ値は入ってない
A=tf.placeholder(tf.int32)
B=tf.placeholder(tf.int32)
seki=A*B

#実行
sess=tf.Session()
print(sess.run(seki,feed_dict={A:3,B:10})) #プレースホルダの中に値を入れて実行
sess.close()

