# -*- coding: utf-8 -*-
"""課題２.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIb1-Z9kk1ZuX5oB3LJJIXRhKtwriIMT
"""

#おまじない
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

varA=tf.Variable(10)  #変数ノードvarA作成
varB=tf.Variable(1)  #変数ノードvarB作成
addAB=tf.add(varA,varB)  #足し算 varA varB
assB=tf.assign(varB,varB*2)  #代入    演算ノード
addA2B=tf.add(varA,assB)  #足し算 varA varB

#実行
sess=tf.Session()  #ノードを実行
(sess.run(tf.global_variables_initializer()))  #変数の場合、初期化する必要がある
print(sess.run(addAB))  #A+B
print(sess.run(addA2B))  #A+2*B

sess.close()

#おまじない
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

varA=tf.Variable(10000)  #変数ノード作成
waruA=tf.floordiv(varA,10) #varAを10で割った整数を入れる
addA=tf.assign(varA,waruA) #varAにwaruAを入れる

#実行
sess=tf.Session()  #おまじない
(sess.run(tf.global_variables_initializer()))  #変数の場合、初期化する必要がある

#varAの値を10で５回割っていく
for i in range(1,6):
  sess.run(waruA)
  print(sess.run(addA))  #5
sess.close()

