# -*- coding: utf-8 -*-
"""課題１.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_LD0yfvTDFLp1YZZMPggiqaJra0hjW-K
"""

import tensorflow.compat.v1 as tf #おまじない
tf.disable_v2_behavior() #おまじない 
import numpy as np #行列を使えるようにするためのライブラリを入れる

const1=tf.constant(7)  #7を出力するノードを作成

#実行
sess=tf.Session()
print(sess.run(const1)) #const1という変数の中の入っている値を得て表示 
sess.close()

import tensorflow.compat.v1 as tf #おまじない
tf.disable_v2_behavior()　#おまじない
import numpy as np 

#それぞれのノードを作成 まだ値は得ていない　この場合、足し算をしてる
const1=tf.constant(7)
const2=tf.constant(8)
add1=tf.add(const1,const2)

#ノードを実行して値を得ている
sess=tf.Session()
print(sess.run(add1))

#おまじない
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

#それぞれ作成したノードと掛け算している
const1=tf.constant(7)
const2=tf.constant(8)
add1=tf.multiply(const1,const2)

#実行かつノードの出力を表示
sess=tf.Session()
print(sess.run(add1))

